export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const EDIT_MODE = 'EDIT_MODE';
export const EDIT_TODO = 'EDIT_TODO';
export const LOAD_TODOS_FROM_LOCALSTORAGE = 'LOAD_TODOS_FROM_LOCALSTORAGE';
